[project]
name = "ai-web-scraper-generator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "autogen-core>=0.5.5",
    "autogen-ext[azure]>=0.5.5",
    "browser-use>=0.1.41",
]
